### PR TITLE
Fix the total energy expression

### PR DESCRIPTION
**Pull request by WbSun723**
Hey Adam, here is a quick fix for the total energy calculations.
Before merging, unittests for total energy calculations should be added and further check should be done :)

### CODE REVIEW

**Review by mcsloy — COMMENTED** [review]
I must admit I am used to seeing the total energy expression in the following form<sup>[1]</sup>:

$E = E_{band} + E_{coul} + E_{rep}$

which expands to:

$E = \sum_{a}f_{a}\sum_{\mu\nu}c^{a}_{\mu}*c^{a} _{\nu}H^{0} _{\mu\nu} + \frac{1}{2} \sum _{ij} \gamma _{ij}(R _{ij})\Delta q _{i} \Delta q _{j} + \sum _{i \lt j} V ^{ij} _{rep}(R _{ij})$

However, I think we need to be careful with how we name things as this does not, at first glace, seem to align with what is written in the DFTB+ "details.out" file.

I think this highlights some things that we need to look at a little more closely. Good work on tracking this issue down. :)

[1] [Density-functional tight-binding for beginners, Pekka Koskinen, Ville Mäkinen,](https://doi.org/10.1016/j.commatsci.2009.07.013)

**Comment by mcsloy** [comment]
Like you say, I think we will need to add some unit tests for this. Later in (in a separate pull request) we will also need to update the SCC unit tests as they currently do not test anything more than the occupancies.

**Comment by mcsloy** [comment]
Great stuff here, Wenbo. So I have finally managed to go through everything that is going on. I have a few suggestions regarding the location and naming of various properties. Let me know what you think. 

#### 1)
Remove `h0_energy` property from the `Dftb1` calculator. This has no meaning within the context of non-scc DFTB as it has no notion of $\text{H}_{0}$ vs $\text{H}_{1}$. Furthermore, this would just return the same result as the `band_energy` property.


#### 2)
While `h0_energy` has meaning and within SCC-DFTB, it might be best to rename it to `core_band_energy`. As this is more consistent with our current naming of `hamiltonian` vs `core_hamiltonian`. 
```python
@property
def core_band_energy(self):
	return ((self.rho * self.core_hamiltonian).sum(-1).sum(-1))
```


#### 3)
Remove the `h2_energy` property the `Dftb1` calculator.  The `h2` value only has meaning within the context of non-SCC DFTB; thus `Dftb1` should have no knowledge of this. Furthermore, this has no meaning within `Dftb2` either, as it will just be equivalent to the `band_energy`.


#### 4)
It might be best to move the computation of the `scc_energy` out of the `_scc_cycle` method, and into its own property like so:
   ```Python
   @property
def scc_energy(self):
	q_delta = _mulliken(self.rho, self.overlap, self.orbs) - self.q_zero_res
	shifts = torch.einsum('...i,...ij->...j', q_delta, self.gamma)  
	return .5 * (shifts * q_delta).sum(-1)
```
This way it is consistent with the other energy properties.

#### 5)
Remove the setter for the `scc_energy` property. Setting the property will no longer have any meaning now that it is computed in an a ad-hoc manner due to the previous suggestion.

#### 6)
Remove the `_scc_energy` attribute as it is no longer required due to the previous two suggestions.

#### 7)
Simplify the total energy in the `Dftb1` calculator to just "`self.band_energy + self.repulsive_energy`" . The `Dftb2` calculator should overwrite this property to "`self.core_band_energy + self.scc_energy + self.repulsive_energy`". While doing this might seem like more work, it would allow the classes to better obey best practices regarding class inheritance.

**Comment by WbSun723** [comment]
Hey Adam, thanks a lot for reviewing! I will make some modifications according to it :)

**Pull request merged**
